- name: Install packages with brew
  become: yes
  community.general.homebrew:
    name:
      - git
      - tmux
      - wget
      - zsh
      - neovim
      - zsh-autosuggestions
    state: present
  when: ansible_distribution == "MacOSX"

