- name: Download Neovim AppImage
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: "{{ ansible_env.HOME }}/nvim.appimage"
    mode: '0755'

- name: Make Neovim AppImage executable
  file:
    path: "{{ ansible_env.HOME }}/nvim.appimage"
    mode: 'u+x'

- name: Run Neovim AppImage
  command: "{{ ansible_env.HOME }}/nvim.appimage --version"
  register: nvim_version
  changed_when: false

- name: Move Neovim AppImage to ~/bin
  command: mv "{{ ansible_env.HOME }}/nvim.appimage" "{{ ansible_env.HOME }}/bin/nvim"
  args:
    creates: "{{ ansible_env.HOME }}/bin/nvim"

- name: Display Neovim version
  debug:
    var: nvim_version.stdout
