- name: Download Neovim tarball
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: /tmp/nvim-linux64.tar.gz

- name: Create a directory for Neovim
  become: yes
  file:
    path: /opt/neovim
    state: directory

- name: Extract Neovim tarball
  become: yes
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /opt/neovim
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Link Neovim binary to /usr/local/bin
  become: yes
  file:
    src: /opt/neovim/bin/nvim
    dest: /usr/local/bin/nvim
    state: link

- name: Remove downloaded Neovim tarball
  file:
    path: /tmp/nvim-linux64.tar.gz
    state: absent

