- name: Change the default shell to Zsh
  shell: chsh -s $(which zsh)
  become: yes

- name: Check if Oh My Zsh is already installed
  stat: 
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_installed
  changed_when: false

- name: Install Oh My Zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    env ZSH="{{ ansible_env.HOME }}/.oh-my-zsh" RUNZSH=no CHSH=no
  args:
    executable: /bin/bash
  become: no
  when: not ohmyzsh_installed.stat.exists

- name: Check if zsh-autosuggestions is already installed
  stat:
    path: "${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  register: autosuggestions_installed
  changed_when: false

- name: Install Autosuggestions
  shell: >
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  args:
    executable: /bin/bash
  become: no
  when: not autosuggestions_installed.stat.exists

